language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2
before_install:
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
install:
- "./Scripts/install.sh"
script:
- "./Scripts/build.sh"
deploy:
  provider: s3
  access_key_id: Alex
  secret_access_key:
    secure: kAg36FUXiC5+PGw3juQLopCibI6T73ENtY7Ubbn4peGGaIGQDQlew3KpzpauWMDobHcZUBZks62lfkMOLvUTpbIMwAxHN/QejV1cdXwKNxwqCJqew9MPoSiojAtKGxToUKVVxFE3ci30qXtx/Aa1lBb1zBZLsRb2yVEoiauUOlM8XyZu55+1jPmOOU6JeDJrL3+lQpmePY14SLyr9SUO56KcOT3E5MAHXoLiSC8KLl0MCpuuNnmBVebOlr7Xqhhtx/zjl9g0J0mMf/VmgdyxEKqf8nsne593K69jv8Tkinyk5wlHuqX2/DBA3D/y7WTKXLhm2wXfO+9WDplI7aN48g29x1b4WJvWCSmnMM74X7k+I2JrBMFhGUYD5eBrTmy6Fic7X866rPJWeVaTuTGxIaFjEPChlFCXriw00yME61m/7Z2MjPtP6EFG74wX4REbtR45uCm4w+Ca7G9dVWKPBD9TNnkN4tckhQ8ZWi/hAWFh56hUf7KWrtDKEiYvjIlQvoHLk8+Rjg3KD+Yf8HpQZ4f/d87EK7mQWNOclIIJyZc0ZfzoVGZXOxnHT553ax03HJr+LVRBuezrkAwTjqu/c17ypeMAW9zcvXTKlB42BU+iMSjDuLRw/7nEFPzIvyfmOKsK7j2jviGeRyvHBuLJYteNk+xZdCcu2tocNGB5AjI=
  bucket: S3 Bucket
  acl: ''
  on:
    repo: utopicstudio/Hansel-Gretel
